// <auto-generated />
namespace NB_PRS_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class appdbchanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appdbchanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201803131533555_appdb changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
