// <auto-generated />
namespace NB_PRS_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class allowingnullsondatesanduserfortesting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(allowingnullsondatesanduserfortesting));
        
        string IMigrationMetadata.Id
        {
            get { return "201803102237293_allowing nulls on dates and user for testing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
